# Copyright (c) 2020, 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
title: "OCI APEX Implemenation using Customer Managed ORDS"
description: "Highly Available/Scalable architecuture running APEX in OCI with Customer Managed ORDS"
informationalText: "This IaC supports 5 different size configurations: ALF (Always Free), XS, S, M, L with variations to the general architecture."
schemaVersion: 1.0.0
version: "20210901"

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "General Configuration"
    variables:
      - label_prefix
      - always_free
      - size
      - adb_license_model
    visible: true

  - title: "Additional Components"
    variables:
      - use_object_storage
      - use_data_safe
      - use_oic
    visible: true

  - title: "Basic Hidden"
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region
      - current_user_ocid
    visible: false

  - title: "Extras Hidden"
    variables:
      - fingerprint
      - private_key_path
    visible: false

  - title: "OCI Services Hidden"
    variables:
      - adb_cpu_core_count
      - adb_dataguard
      - flex_lb_min_shape
      - flex_lb_max_shape
      - compute_instances
      - compute_flex_shape_ocpus
      - adb_storage_size_in_tbs
      - adb_db_version
      - compute_image
      - linux_os_version
      - bastion_user
      - vcn_cidr
      - vcn_is_ipv6enabled
      - public_subnet_cidr
      - private_subnet_cidr
      - enable_lbaas_ruleset
    visible: false

  - title: "Locals Hidden"
    variables:
      - compute_flexible_shapes
      - is_paid
      - adb_private_endpoint
      - compute_shape
      - is_flexible_shape
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  label_prefix:
    type: string
    title: "Resource Name Prefix"
    default: "apexpoc"
    required: true

  always_free:
    type: boolean
    title: "Always Free Resources"
    default: false

  size:
    type: enum
    title: "Architecture Size"
    default: "ALF"
    enum:
      - XS
      - S
      - M
      - L
    required: true
    visible:
      not:
        - always_free

  adb_license_model:
    type: enum
    title: "ADB License"
    default: "BRING_YOUR_OWN_LICENSE"
    enum:
      - BRING_YOUR_OWN_LICENSE
      - LICENSE_INCLUDED
    required: true
    visible:
      not:
        - always_free

  prov_object_storage:
    type: boolean
    title: "Provision Object Storage"
    default: false

  enable_lb_logging:
    type: boolean
    title: "Enable Load Balancer Logging"
    default: false

  prov_data_safe:
    type: boolean
    title: "Provision Data Safe"
    default: false
    visible:
      not:
        - always_free

  prov_oic:
    type: boolean
    title: "Provision Oracle Integration Cloud"
    default: false
    visible:
      not:
        - always_free

outputs:
  lb_address:
    title: "Load Balancer Public IP"
    displayText: ${Messages.solutionsHub.solutions.ociDevTools.outputs.lb_address.displayText()}
    type: copyableString
    visible: true
